### PR TITLE
Interface rework - Adding Logs & Players names display

### PR DESCRIPTION
**Pull request by NekoSelena**

### CODE REVIEW

**Comment by Trompettesib** [comment]
I hate you with your github desktop tricks

**Comment by NekoSelena** [comment]
As there is no way to get the players names, for now it is done that way, but will be changed after #37 is resolved.

**Comment by huntears** [comment]
How do I test it ?

**Review by huntears — APPROVED** [review]

**Review by Trompettesib — APPROVED** [review]
LGTM don't forget to remove useless comments 😉

**Pull request merged**
