### PR TITLE
Fix race conditions in chunk sending after gen

### LINKED ISSUE #220: Race condition on chunk generation
Sometimes an access to the chunk column map will fail and permanently lock a chunk to the void.

### PR DESCRIPTION
**Pull request by huntears**
This was awfully simple to fix, just a mutex to lock ;w;

Fixes #220

### CODE REVIEW

**Review by Trompettesib — APPROVED** [review]

**Comment by STMiki** [comment]
Doesn't this disable multi threaded generation ?

**Review by STMiki — CHANGES_REQUESTED** [review]
I think you could try to use a shared lock instead of a recursive one,
but as-is this completely disable multi threaded generation.
And there is [one more place](https://github.com/CubicMC/cubic-server/blob/b9a2bf444c5dd541cf725d55494ca439e7360c49/cubic-server/default/Overworld.cpp#L37) where we generate chunk

**Review by STMiki — APPROVED** [review]
Don't forget to open an issue

**Review by Trompettesib — APPROVED** [review]
looks fine

**Pull request merged**
