### PR TITLE
Adding automation and tests

### PR DESCRIPTION
**Pull request by Trompettesib**

### CODE REVIEW

**Comment by huntears** [comment]
You may want to change the compiler for the CI from gcc to clang

**Comment by Trompettesib** [comment]
How can I do to start another time this action ?

**Comment by Trompettesib** [comment]
If this is possible, I want to remove the last two commit from this PR because they are only for GTests things and not about the "pure" CI. I would like to do another PR only for this two commits (if this is relevent of course)
I don't know how to do that ^^ this is why I write it there ^^

**Review by huntears — DISMISSED** [review]
LGTM

**Pull request merged**
