### PR TITLE
Add NBT types + serialization

### PR DESCRIPTION
**Pull request by huntears**
It should just work.
The only thing that could be made better later down the line would be `nbt::List`, it only throws an exception for multiple types at serialization, not during initialization.

### CODE REVIEW

**Comment by huntears** [comment]
Some problems are in this PR, currently fixing.

**Comment by Trompettesib** [comment]
Testing it with google test would have been perfect

**Review by Trompettesib — APPROVED** [review]
LGTM

**Review by Trompettesib — APPROVED** [review]
👌

**Review by STMiki — APPROVED** [review]
👌

**Pull request merged**
