### PR TITLE
Add generation structure files

### PR DESCRIPTION
**Pull request by LEVRAIBHL**

### CODE REVIEW

**Review by huntears — CHANGES_REQUESTED** [review]
Can't approve when there is no code.

**Review by STMiki — CHANGES_REQUESTED** [review]
`Structures need to be generated in the world according to given settings files. The "salt" of the structures need to be accounted for`

This was one of the requirement of the task that was given to you, and this is clearly not done.

If you are still working on this, change this to draft

**Review by NekoSelena — CHANGES_REQUESTED** [review]
Generation is still missing, nothing happens as it is. Some code is needed for it to work.

Please work again through it before I can accept your changes.

**Review by Trompettesib — CHANGES_REQUESTED** [review]
I don't know if it works on your pc, but on mine, the structure is not generated (even if I change the spacing).
As STMiki said, if you are still working on this, you have to put this pull request in draft :)

**Comment by huntears** [comment]
I am closing this PR for the following reasons : 
- No contact from the creator
- No code whatsoever
- Copy paste of a datapack template

**Pull request closed without merging**
